---
- name: Install and Configure CKAN on Ubuntu 22.04 with HTTPS and OIDC
  hosts: ckan_servers
  become: true
  vars_files:
    - group_vars/vault.yml
  
  vars:
    ckan_version: "2.11"
    solr_version: "9.5.0"
    ckan_domain: "dc.cyverse.org"
    ckan_site_url: "https://{{ ckan_domain }}"
    ckan_storage_path: "/var/lib/ckan/default/storage"
    ssl_certificate_path: "/etc/ssl/certs/cyverse.org.pem"
    ssl_certificate_key_path: "/etc/ssl/private/cyverse.org.key"
    
    # OIDC Configuration - Keycloak
    oidc_base_url: "https://kc.cyverse.org/auth"
    oidc_realm: "CyVerse"
    oidc_auth_path: "/realms/{{ oidc_realm }}/protocol/openid-connect/auth"
    oidc_token_path: "/realms/{{ oidc_realm }}/protocol/openid-connect/token"
    oidc_userinfo_path: "/realms/{{ oidc_realm }}/protocol/openid-connect/userinfo"
    oidc_redirect_path: " /local/oidc/handler"
    oidc_scope: "openid email profile"
    oidc_use_same_id: true
    oidc_munge_password: true
    
  tasks:
    - name: Update system packages
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - libpq5
          - nginx
          - postgresql
          - postgresql-contrib
          - redis-server
          - supervisor
          - xz-utils
          - python3-pip
          - python3-venv
          - python3-dev
          - libpq-dev
          - git
          - openjdk-11-jdk
          - wget
          - curl
          - lsof
          - python3-psycopg2
        state: present

    - name: Verify SSL certificate exists
      ansible.builtin.stat:
        path: "{{ ssl_certificate_path }}"
      register: ssl_cert_file
      failed_when: not ssl_cert_file.stat.exists

    - name: Verify SSL private key exists
      ansible.builtin.stat:
        path: "{{ ssl_certificate_key_path }}"
      register: ssl_key_file
      failed_when: not ssl_key_file.stat.exists

    - name: Display SSL certificate status
      ansible.builtin.debug:
        msg: "Using existing SSL certificates at {{ ssl_certificate_path }} and {{ ssl_certificate_key_path }}"

    - name: Create Java environment script
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          export PATH="$JAVA_HOME/bin:$PATH"
        dest: /etc/profile.d/java.sh
        mode: '0755'
        owner: root
        group: root

    - name: Source Java environment for current session
      ansible.builtin.shell: source /etc/profile.d/java.sh
      args:
        executable: /bin/bash

    - name: Verify Java installation
      ansible.builtin.command: /usr/lib/jvm/java-11-openjdk-amd64/bin/java -version
      register: java_version
      failed_when: java_version.rc != 0

    - name: Display Java version
      ansible.builtin.debug:
        msg: "Java version: {{ java_version.stderr_lines[0] }}"

    - name: Start and enable PostgreSQL
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: true

    # - name: Start and enable Redis
    #   ansible.builtin.systemd:
    #     name: redis-server
    #     state: started
    #     enabled: true

    - name: Create CKAN database user
      become_user: postgres
      postgresql_user:
        name: "{{ ckan_db_user }}"
        password: "{{ ckan_db_password }}"
        role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
        state: present

    - name: Create CKAN database
      become: yes
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ ckan_db_name }}"
        owner: "{{ ckan_db_user }}"
        encoding: "UTF-8"
        template: "template0"
        state: present

    - name: Download CKAN package
      ansible.builtin.get_url:
        url: "https://packaging.ckan.org/python-ckan_{{ ckan_version }}-jammy_amd64.deb"
        dest: "/tmp/python-ckan_{{ ckan_version }}-jammy_amd64.deb"
        mode: '0644'

    - name: Install CKAN package
      ansible.builtin.apt:
        deb: "/tmp/python-ckan_{{ ckan_version }}-jammy_amd64.deb"
        state: present

    - name: Create CKAN directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
      loop:
        - /var/lib/ckan
        - /var/lib/ckan/default
        - /var/lib/ckan/default/storage
        - /var/lib/ckan/default/webassets
        - /etc/ckan
        - /etc/ckan/default
        - /var/log/ckan

    - name: Check if Solr service files exist
      ansible.builtin.stat:
        path: "/opt/solr/bin/solr"
      register: solr_service_files

    - name: Download and extract Solr
      ansible.builtin.unarchive:
        src: "https://archive.apache.org/dist/solr/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: /opt
        remote_src: true
        owner: root
        group: root
      when: not solr_service_files.stat.exists

    - name: Create Solr user
      ansible.builtin.user:
        name: solr
        system: yes
        shell: /bin/bash
        home: /var/solr
        create_home: yes
        state: present

    - name: Create Solr directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: solr
        group: solr
        mode: '0755'
      loop:
        - /var/solr
        - /var/solr/data
        - /var/solr/logs

    - name: Copy Solr installation files to /opt/solr
      ansible.builtin.shell: |
        mkdir -p /opt/solr
        cp -r /opt/solr-{{ solr_version }}/* /opt/solr/
        chown -R solr:solr /opt/solr
      args:
        creates: /opt/solr/bin/solr

    - name: Create Solr systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/solr.service
        content: |
          [Unit]
          Description=Apache Solr
          After=network.target
          
          [Service]
          Type=forking
          User=solr
          Group=solr
          WorkingDirectory=/opt/solr
          ExecStart=/opt/solr/bin/solr start -p 8983
          ExecStop=/opt/solr/bin/solr stop
          Restart=on-failure
          RestartSec=5
          
          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable Solr
      ansible.builtin.systemd:
        name: solr
        state: started
        enabled: true

    - name: Wait for Solr to be ready
      ansible.builtin.wait_for:
        port: 8983
        delay: 10
        timeout: 60

    - name: Check if CKAN core exists in Solr
      ansible.builtin.uri:
        url: "http://localhost:8983/solr/admin/cores?action=STATUS&core=ckan"
        method: GET
      register: solr_core_check
      failed_when: false

    - name: Create Solr core for CKAN
      become: true
      become_user: solr
      ansible.builtin.shell: |
        /opt/solr/bin/solr create -c ckan
      args:
        creates: /var/solr/data/ckan
      when: "'ckan' not in (solr_core_check.content | default(''))"

    - name: Download CKAN Solr schema
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ckan/ckan/refs/heads/{{ ckan_version }}/ckan/config/solr/schema.xml"
        dest: /tmp/ckan_schema.xml
        mode: '0644'

    - name: Replace Solr schema with CKAN schema
      ansible.builtin.copy:
        src: /tmp/ckan_schema.xml
        dest: /var/solr/data/ckan/conf/managed-schema.xml
        remote_src: true
        owner: solr
        group: solr
        mode: '0644'
      notify: Restart Solr

    - name: Wait for Solr to be ready after restart
      ansible.builtin.wait_for:
        port: 8983
        delay: 10
        timeout: 60

    # OIDC PKCE Extension Installation
    - name: Install ckanext-oidc-pkce in CKAN virtual environment
      ansible.builtin.pip:
        name: ckanext-oidc-pkce
        virtualenv: /usr/lib/ckan/default
        state: present

    - name: Generate session secret if not provided
      ansible.builtin.shell: python3 -c 'import os; import binascii; print(binascii.hexlify(os.urandom(32)).decode())'
      register: session_secret
      when: ckan_session_secret is not defined

    - name: Set session secret variable
      ansible.builtin.set_fact:
        ckan_session_secret: "{{ session_secret.stdout }}"
      when: session_secret.stdout is defined

    - name: Create CKAN configuration file with OIDC settings
      ansible.builtin.copy:
        dest: /etc/ckan/default/ckan.ini
        content: |
          [app:main]
          use = egg:ckan
          
          ## Database Settings
          sqlalchemy.url = postgresql://{{ ckan_db_user }}:{{ ckan_db_password }}@localhost/{{ ckan_db_name }}
          
          ## Site Settings  
          ckan.site_url = {{ ckan_site_url }}
          ckan.site_id = {{ ckan_site_id | default('default') }}

          ## Authentication Settings
          ckan.auth.user_create_organizations = False
          ckan.auth.create_user_via_web = False
          ckan.auth.public_user_details = False
          ckan.auth.create_dataset_if_not_in_organization = False
          ckan.auth.user_create_groups = False
          ckan.auth.user_delete_groups = False
          
          ## Solr Settings
          solr_url = http://127.0.0.1:8983/solr/ckan
          
          ## Plugins - OIDC PKCE enabled
          ckan.plugins = stats text_view image_view activity oidc_pkce
          
          ## Storage Settings
          ckan.storage_path = {{ ckan_storage_path }}
          
          ## Session Settings
          beaker.session.key = ckan
          beaker.session.secret = {{ ckan_session_secret }}
          
          ## OIDC PKCE Configuration
          # Base URL of the OIDC provider (Keycloak)
          ckanext.oidc_pkce.base_url = {{ oidc_base_url }}
          
          # Client credentials from Keycloak
          ckanext.oidc_pkce.client_id = {{ oidc_client_id }}
          ckanext.oidc_pkce.client_secret = {{ oidc_client_secret }}
          
          # Keycloak-specific OIDC endpoints
          ckanext.oidc_pkce.auth_path = {{ oidc_auth_path }}
          ckanext.oidc_pkce.token_path = {{ oidc_token_path }}
          ckanext.oidc_pkce.userinfo_path = {{ oidc_userinfo_path }}
          
          # Callback path for OIDC authentication
          ckanext.oidc_pkce.redirect_path = {{ oidc_redirect_path }}
          
          # OAuth scopes
          ckanext.oidc_pkce.scope = {{ oidc_scope }}
          
          # Use same user ID from SSO provider
          ckanext.oidc_pkce.use_same_id = {{ oidc_use_same_id }}
          
          # Prevent password-based login for SSO users
          ckanext.oidc_pkce.munge_password = {{ oidc_munge_password }}
          
          ## Logging configuration
          [loggers]
          keys = root, ckan, ckanext
          
          [handlers]
          keys = console
          
          [formatters]
          keys = generic
          
          [logger_root]
          level = WARNING
          handlers = console
          
          [logger_ckan]
          level = INFO
          handlers = console
          qualname = ckan
          propagate = 0
          
          [logger_ckanext]
          level = DEBUG
          handlers = console
          qualname = ckanext
          propagate = 0
          
          [handler_console]
          class = StreamHandler
          args = (sys.stderr,)
          level = NOTSET
          formatter = generic
          
          [formatter_generic]
          format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
        owner: www-data
        group: www-data
        mode: '0640'

    - name: Check if CKAN database is already initialized
      ansible.builtin.shell: |
        cd /usr/lib/ckan/default
        bin/ckan -c /etc/ckan/default/ckan.ini db status
      environment:
        CKAN_INI: /etc/ckan/default/ckan.ini
      register: ckan_db_status
      failed_when: false
      changed_when: false

    - name: Initialize CKAN database
      ansible.builtin.shell: |
        cd /usr/lib/ckan/default
        bin/ckan -c /etc/ckan/default/ckan.ini db init
      environment:
        CKAN_INI: /etc/ckan/default/ckan.ini
      when: ckan_db_status.rc != 0 or 'database is not set up' in ckan_db_status.stderr | lower

    - name: Display message if admin credentials not defined
      ansible.builtin.debug:
        msg: "Admin user creation skipped - ckan_admin_user, ckan_admin_email, and/or ckan_admin_password not defined in vault.yml"
      when: 
        - ckan_admin_user is not defined or ckan_admin_email is not defined or ckan_admin_password is not defined

    - name: Check if CKAN admin user already exists
      ansible.builtin.shell: |
        cd /usr/lib/ckan/default
        bin/ckan -c /etc/ckan/default/ckan.ini user show {{ ckan_admin_user }}
      environment:
        CKAN_INI: /etc/ckan/default/ckan.ini
      register: user_exists
      failed_when: false
      changed_when: false
      when: 
        - ckan_admin_user is defined
        - ckan_admin_email is defined
        - ckan_admin_password is defined

    - name: Create CKAN admin user
      ansible.builtin.shell: |
        cd /usr/lib/ckan/default
        echo "y" | bin/ckan -c /etc/ckan/default/ckan.ini user add {{ ckan_admin_user }} email={{ ckan_admin_email }} password={{ ckan_admin_password }}
        bin/ckan -c /etc/ckan/default/ckan.ini sysadmin add {{ ckan_admin_user }}
      environment:
        CKAN_INI: /etc/ckan/default/ckan.ini
      when: 
        - ckan_admin_user is defined
        - ckan_admin_email is defined
        - ckan_admin_password is defined
        - user_exists.rc != 0

    - name: Display admin user creation status
      ansible.builtin.debug:
        msg: "Admin user '{{ ckan_admin_user }}' already exists - skipping creation"
      when: 
        - ckan_admin_user is defined
        - user_exists.rc == 0

    - name: Check for existing CKAN processes
      ansible.builtin.shell: |
        pgrep -f "ckan.*(run|serve)" || echo "no_processes"
      register: ckan_processes
      changed_when: false
      failed_when: false

    - name: Kill existing CKAN processes if found
      ansible.builtin.shell: |
        pkill -f "ckan.*run"
        pkill -f "ckan.*serve"
        sleep 2
      when: ckan_processes.stdout != "no_processes" and ckan_processes.stdout != ""
      ignore_errors: true

    - name: Create CKAN supervisor configuration
      ansible.builtin.copy:
        dest: /etc/supervisor/conf.d/ckan.conf
        content: |
          [program:ckan]
          command=/usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini run --host 0.0.0.0 --port 5000
          autostart=true
          autorestart=true
          redirect_stderr=true
          stdout_logfile=/var/log/ckan/ckan.log
          stderr_logfile=/var/log/ckan/ckan.error.log
          user=www-data
          environment=CKAN_INI="/etc/ckan/default/ckan.ini"
        mode: '0644'

    - name: Update supervisor
      ansible.builtin.shell: |
        supervisorctl reread
        supervisorctl update

    - name: Start CKAN via supervisor
      ansible.builtin.supervisorctl:
        name: ckan
        state: restarted

    - name: Wait for CKAN to be ready on port 5000
      ansible.builtin.wait_for:
        port: 5000
        delay: 5
        timeout: 60

    - name: Configure Nginx for CKAN with HTTPS
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/ckan
        content: |
          # HTTP - Redirect to HTTPS
          server {
              listen 80;
              server_name {{ ckan_domain }};
              return 301 https://$server_name$request_uri;
          }
          
          # HTTPS
          server {
              listen 443 ssl http2;
              server_name {{ ckan_domain }};
              client_max_body_size 100M;
              
              # SSL Configuration
              ssl_certificate {{ ssl_certificate_path }};
              ssl_certificate_key {{ ssl_certificate_key_path }};
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_ciphers HIGH:!aNULL:!MD5;
              ssl_prefer_server_ciphers on;
              
              # SSL Session Cache
              ssl_session_cache shared:SSL:10m;
              ssl_session_timeout 10m;
              
              # Security Headers
              add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
              add_header X-Frame-Options SAMEORIGIN;
              add_header X-Content-Type-Options nosniff;
              add_header X-XSS-Protection "1; mode=block";
              
              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header X-Forwarded-Host $host;
                  proxy_buffering off;
                  proxy_request_buffering off;
              }
          }
        mode: '0644'

    - name: Enable Nginx CKAN site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/ckan
        dest: /etc/nginx/sites-enabled/ckan
        state: link

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test Nginx configuration
      ansible.builtin.shell: nginx -t
      register: nginx_test

    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
      when: nginx_test.rc == 0

    - name: Wait for HTTPS to be ready
      ansible.builtin.wait_for:
        port: 443
        delay: 5
        timeout: 30

    - name: Test CKAN availability via HTTPS
      ansible.builtin.uri:
        url: "https://{{ ckan_domain }}"
        method: GET
        status_code: [200, 302]
        validate_certs: yes
      register: ckan_test
      retries: 5
      delay: 10
      until: ckan_test.status in [200, 302]

    - name: Verify CKAN is responding correctly
      ansible.builtin.fail:
        msg: "CKAN failed to start properly. Check logs at /var/log/ckan/ckan.log and /var/log/ckan/ckan.error.log"
      when: ckan_test.status not in [200, 302]

    - name: Display CKAN access information
      ansible.builtin.debug:
        msg:
          - "======================================"
          - "CKAN installation with OIDC completed!"
          - "======================================"
          - "Access CKAN at: https://{{ ckan_domain }}"
          - "OIDC Login: https://{{ ckan_domain }}/user/login/oidc-pkce"
          - "Admin user: {{ ckan_admin_user | default('Not created - define in vault') }}"
          - ""
          - "SSL Certificate: {{ ssl_certificate_path }}"
          - "SSL Private Key: {{ ssl_certificate_key_path }}"
          - ""
          - "OIDC Provider: {{ oidc_base_url }}"
          - "OIDC Realm: {{ oidc_realm }}"
          - "OIDC Client: {{ oidc_client_id }}"
          - ""
          - "Check status with:"
          - "  sudo supervisorctl status ckan"
          - "  sudo systemctl status solr"
          - "  sudo systemctl status nginx"
          - "  sudo tail -f /var/log/ckan/ckan.log"
          - "======================================"

  handlers:
    - name: Restart Solr
      ansible.builtin.systemd:
        name: solr
        state: restarted

    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted