---
- name: Install and Configure CKAN on Ubuntu 22.04
  hosts: ckan_servers
  become: true
  vars_files:
    - group_vars/vault.yml

  tasks:
    - name: Update system packages
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required dependencies
      ansible.builtin.package:
        name:
          - libpq5
          - nginx
          - postgresql
          - redis-server
          - supervisor
          - xz-utils
        state: present

    # - name: Install required dependencies
    #   apt:
    #     name:
    #       - nginx
    #       - openjdk-11-jdk
    #       - postgresql
    #       - python3-pip
    #       - redis-server
    #       - supervisor
    #       - unzip
    #       - wget
    #     state: present

    - name: Install CKAN
      ansible.builtin.apt:
        deb: https://packaging.ckan.org/python-ckan_2.11-jammy_amd64.deb

    - name: Start PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Create CKAN database user
      shell: |
        sudo -u postgres psql -c "CREATE ROLE {{ ckan_db_user }} WITH LOGIN PASSWORD '{{ ckan_db_password }}' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
      ignore_errors: yes

    - name: Create CKAN database
      shell: sudo -u postgres createdb -O {{ ckan_db_user }} {{ ckan_db_name }} -E utf-8
      ignore_errors: yes

    - name: Create datastore user
      shell: |
        sudo -u postgres psql -c "CREATE ROLE {{ datastore_user }} WITH LOGIN PASSWORD '{{ datastore_password }}' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
        sudo -u postgres psql -c "GRANT CONNECT ON DATABASE {{ ckan_db_name }} TO {{ datastore_user }};"
      ignore_errors: yes

    - name: Set permissions for CKAN directories
      file:
        path: /var/lib/ckan/default
        state: directory
        owner: www-data
        group: www-data
        mode: 0775

    - name: Download CKAN package
      get_url:
        url: "https://packaging.ckan.org/python-ckan_{{ ckan_version }}-jammy_amd64.deb"
        dest: "/tmp/python-ckan_{{ ckan_version }}-jammy_amd64.deb"

    - name: Install CKAN package
      command: dpkg -i /tmp/python-ckan_{{ ckan_version }}-jammy_amd64.deb
      ignore_errors: yes

    - name: Fix missing dependencies
      command: apt-get install --fix-broken -y

    - name: Fix permissions for webassets
      file:
        path: /var/lib/ckan/default/webassets
        state: directory
        owner: www-data
        group: www-data
        mode: 0775

    - name: Ensure CKAN configuration file is in place
      template:
        src: ckan.ini.j2
        dest: /etc/ckan/default/ckan.ini
        owner: www-data
        group: www-data
        mode: 0644

    - name: Download and install Solr
      ansible.builtin.unarchive:
        src: https://archive.apache.org/dist/solr/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
        dest: /opt
        creates: /opt/solr-{{ solr_version }}
        remote_src: true

    - name: Start Solr
      shell: nohup /opt/solr-{{ solr_version }}/bin/solr start &
      ignore_errors: yes

    - name: Create Solr core for CKAN
      command: /opt/solr-{{ solr_version }}/bin/solr create -c ckan
      ignore_errors: yes

    - name: Start CKAN
      shell: nohup /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini run > /dev/null 2>&1 &
      args:
        executable: /bin/bash
      ignore_errors: yes
