---
- name: Install and Configure CKAN on Ubuntu 22.04
  hosts: ckan_servers
  become: yes
  vars_files:
    - group_vars/vault.yml

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - python3-pip
          - libpq5
          - redis-server
          - nginx
          - supervisor
          - postgresql
          - openjdk-11-jdk
          - unzip
          - wget
        state: present

    - name: Start PostgreSQL (WSL / Remote)
      command: service postgresql start
      ignore_errors: yes

    - name: Create CKAN database user
      shell: |
        sudo -u postgres psql -c "CREATE ROLE {{ ckan_db_user }} WITH LOGIN PASSWORD '{{ ckan_db_password }}' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
      ignore_errors: yes

    - name: Create CKAN database
      shell: sudo -u postgres createdb -O {{ ckan_db_user }} {{ ckan_db_name }} -E utf-8
      ignore_errors: yes

    - name: Create datastore user
      shell: |
        sudo -u postgres psql -c "CREATE ROLE {{ datastore_user }} WITH LOGIN PASSWORD '{{ datastore_password }}' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
        sudo -u postgres psql -c "GRANT CONNECT ON DATABASE {{ ckan_db_name }} TO {{ datastore_user }};"
      ignore_errors: yes

    - name: Set permissions for CKAN directories
      file:
        path: /var/lib/ckan/default
        state: directory
        owner: www-data
        group: www-data
        mode: 0775

    - name: Download CKAN package
      get_url:
        url: "https://packaging.ckan.org/python-ckan_{{ ckan_version }}-jammy_amd64.deb"
        dest: "/tmp/python-ckan_{{ ckan_version }}-jammy_amd64.deb"

    - name: Install CKAN package
      command: dpkg -i /tmp/python-ckan_{{ ckan_version }}-jammy_amd64.deb
      ignore_errors: yes

    - name: Fix missing dependencies
      command: apt-get install --fix-broken -y

    - name: Fix permissions for webassets
      file:
        path: /var/lib/ckan/default/webassets
        state: directory
        owner: www-data
        group: www-data
        mode: 0775

    - name: Ensure CKAN configuration file is in place
      copy:
        src: /etc/ckan/default/ckan.ini
        dest: /etc/ckan/default/ckan.ini
        owner: www-data
        group: www-data
        mode: 0644
        remote_src: yes

    - name: Download and install Solr
      shell: |
        wget -O /tmp/solr.tgz https://dlcdn.apache.org/solr/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
        tar xzf /tmp/solr.tgz -C /opt/
      args:
        creates: "/opt/solr-{{ solr_version }}"

    - name: Start Solr
      shell: nohup /opt/solr-{{ solr_version }}/bin/solr start &
      ignore_errors: yes

    - name: Create Solr core for CKAN
      command: /opt/solr-{{ solr_version }}/bin/solr create -c ckan
      ignore_errors: yes

    - name: Start CKAN
      shell: nohup /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini run > /dev/null 2>&1 &
      args:
        executable: /bin/bash
      ignore_errors: yes